[package]
name = "pommet"
version = "0.1.0"
edition = "2024"

[dependencies]
bzip2 = "0.5.2"
crossterm = "0.29.0"
ratatui = "0.29.0"
tar = "0.4.44"
reqwest = { version = "0.12,0", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3"
zip = "4.0.0"
